export const projects = [
  {
    title: "JamSpace",
    description: "Online marketplace that connects people with musical instruments they want to rent out to people who want to rent instruments.", 
    techStack: ["MongoDB", "Express", "React", "Node.js", "Bootstrap", "MUI", "API"],
    githubLink: "https://noahthomlison.github.io/JamSpace/",
    image: ["https://github.com/NoahThomlison/JamSpace/blob/master/screenshots/Home_Page.gif?raw=true"],
  },
  {
    title: "TinyApp ",
    description: "TinyApp is a full stack web application built with Node and Express that allows users to shorten long URLs", 
    techStack: ["JS", "Express", "Node.js", "EJS"],
    githubLink: "https://noahthomlison.github.io/tinyapp/",
    image: ["https://noahthomlison.github.io/tinyapp/TinyApp.gif"],
  },
  {
    title: "Jungle",
    description: "A mini e-commerce application built with Rails 4.2 for purposes of teaching Rails by example. ", 
    techStack: ["Ruby", "Rails", "PostgreSQL", "ActiveRecord"],
    githubLink: "https://noahthomlison.github.io/jungle-rails/",
    image: ["https://noahthomlison.github.io/jungle-rails/jungleFiltering.gif"],
  },
  {
    title: "Tweeter",
    description: "Tweeter is a simple, single-page Twitter clone. ", 
    techStack: ["HTML", "CSS", "JS", "jQuery", "Ajax", "Node.js", "Express", "MongoDB"],
    githubLink: "noahthomlison.github.io/tweeter/",
    image: ["https://user-images.githubusercontent.com/80222250/157595393-7c51d08e-bd96-4151-b718-0920cd30c165.gif"],
  },
  {
    title: "LightBnB",
    description: "LightBNB is an Lighthouse Labs AirBNB clone", 
    techStack: ["JS", "SASS", "Node.js", "Express", "PostgreSQL"],
    githubLink: "noahthomlison.github.io/lightbnb/",
    image: ["https://noahthomlison.github.io/LightBnB/LightBNB.gif"],
  },
  {
    title: "Scheduler",
    description: "Interview Scheduler is a single-page application (SPA) that allows users to book technical interviews between students and mentors.", 
    techStack: ["React", "Cypress", "Storybook", "Jest", "Express"],
    githubLink: "https://github.com/NoahThomlison/scheduler",
    image: ["https://user-images.githubusercontent.com/80222250/144094594-abfc858f-0c51-424d-aa53-9bbd9f70eac8.png"],
  },
  {
    title: "Smart-To-Do-List",
    description: "The Smart To Do List is a self sorting to do list where a user can enter a keyword/task and the app will sort it into a predefined category", 
    techStack: ["JS", "EJS", "Express", "Node.js", "API"],
    githubLink: "https://github.com/NoahThomlison/SmartToDoList",
    image: ["https://user-images.githubusercontent.com/80222250/139961316-9f2cf2d0-fee7-4b99-ae1b-5ba287cf6ea3.png"],
  },
]